{% set version = "0.1.3" %}

package:
  name: pymt_child
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_child/archive/v{{ version }}.tar.gz
  sha256: 1e549c9ffdf947d8ae61413b9183e59005301d288e45bdf74e361924944350d8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win or py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - child
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - child

test:
  imports:
    - pymt_child

about:
  home: http://github.com/mcflugen/pymt_child
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Child landscape evolution model wrapped as a PyMT plugin
  dev_url: http://github.com/mcflugen/pymt_child

extra:
  recipe-maintainers:
    - mcflugen
