{% set version = "0.1.1" %}

package:
  name: pymt_child
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_child/archive/v{{ version }}.tar.gz
  sha256: ec2fe44a8a942c797a4c3bbc87d40e8421e89dfe1394799621be8d8f02b91b5f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win or linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3
    - pip
    - cython
    - numpy
    - model_metadata
    - child
  run:
    - python >=3
    - {{ pin_compatible('numpy') }}
    - child

test:
  imports:
    - pymt_child

about:
  home: http://github.com/mcflugen/pymt_child
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Child landscape evolution model wrapped as a PyMT plugin
  dev_url: http://github.com/mcflugen/pymt_child

extra:
  recipe-maintainers:
    - mcflugen
