{% set version = "0.1.2" %}

package:
  name: pymt_child
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_child/archive/v{{ version }}.tar.gz
  sha256: 6e8d6f87da9376145db73979da89d2bb4074e1a805449df95a60bee8f7b382a0

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win or linux or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - model_metadata
    - child
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - child

test:
  imports:
    - pymt_child

about:
  home: http://github.com/mcflugen/pymt_child
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Child landscape evolution model wrapped as a PyMT plugin
  dev_url: http://github.com/mcflugen/pymt_child

extra:
  recipe-maintainers:
    - mcflugen
