{% set version = "0.2.1" %}

package:
  name: pymt_child
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_child/archive/v{{ version }}.tar.gz
  sha256: f60f876c7ca5bfe83eedcb4fbb8b6be0386c203e13b3aa531e99cb4fcea259e2

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - bmi-cxx
    - child >=21.03.12
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - child >=21.03.12

test:
  requires:
    - bmi-tester
  imports:
    - pymt_child
  commands:
    - bmi-test pymt_child:Child -vvv

about:
  home: http://github.com/mcflugen/pymt_child
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Child landscape evolution model wrapped as a PyMT plugin
  dev_url: http://github.com/mcflugen/pymt_child

extra:
  recipe-maintainers:
    - mcflugen
