travis:
  secure:
    BINSTAR_TOKEN: NdA0K1AriMCRLRd6DbySKO2i4qYCi+mVH6HBoM++Ngit3RUxVn4QOFDQ+wQsuhkSIBtnlLl43JxZYH+wnpYt0fdd+bhYc9a6zNAz6iL6cBsrWwlbRVj603F1RGLoH+fEybO9P8IjpwUpKPaXztJMsdPA0a7sxcioifouTR5aE6esvlUCC8jlwrPWs+JP0rAwGjmpvhDhS+F2ai5jjPcdu7IBCag5zUmqCxp5i2e6weRSdxzNHY7h+V42I9poNVzojBreHiuixYGbzI9CmfYV6wos9t58f0RVVz/jSU8TtSVCFhZnWw3dnG9JL+IUqkpm6zkb3J8gdHPMO5dMSPhkoGwbOT4yvOFqLzzAzvhxKUQNj2i6NCB5zHk/xSwRX+37QZxgU1A31DO2P1VkUEs9+3Q/y4VDArizyXxFSnBb7r2YzLbYnhmooVy/Zu6i6XDPCXBLn4P+UNPHRxBiYo35VciUxuOmGAxNGP1txbh1HNwh2zkr2PqkQe88XY0e8uLrUMJpu9J8O2nyonOkHtJ4zTpr8IGKXG/jKo2JLNuKjoulhCs4MAnJm4x2EY84+CqxXB+IGXkv6KeYT8fwlnDSPRE5RmSBtSDgZPX0NWkBe1z2PatLGQBgqLfbkziPfLtid57X5bOpFSNITLeXsKUjBxoS7hfIRp29AjKKdiqMuZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
